CREATE TABLE player_splits (
    id SERIAL PRIMARY KEY,
    sport VARCHAR(50) NOT NULL,
    player_name VARCHAR(100) NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    split_type VARCHAR(50) NOT NULL,
    split_value VARCHAR(100) NOT NULL,
    season INTEGER NOT NULL,
    at_bats INTEGER,
    runs INTEGER,
    hits INTEGER,
    doubles INTEGER,
    triples INTEGER,
    home_runs INTEGER,
    rbi INTEGER,
    walks INTEGER,
    strikeouts INTEGER,
    stolen_bases INTEGER,
    caught_stealing INTEGER,
    batting_avg FLOAT,
    on_base_pct FLOAT,
    slugging_pct FLOAT,
    ops FLOAT,
    source VARCHAR(100),
    stat_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);