# Team Stats Scraper
import os
import time
import pandas as pd
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

BASE_DIR = "/Users/kamahl/BLOG_AI/sports_scripts/teamrankings/MLB/stats/team_stats/"
os.makedirs(BASE_DIR, exist_ok=True)

def fetch_and_save_table(url, category, filename):
    output_dir = os.path.join(BASE_DIR, category)
    os.makedirs(output_dir, exist_ok=True)
    
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--user-agent=Mozilla/5.0")

    driver = webdriver.Chrome(options=options)
    print(f"Fetching: {url}")
    driver.get(url)

    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, "tr-table"))
        )
        time.sleep(2)
        tables = driver.find_elements(By.CLASS_NAME, "tr-table")

        for table in tables:
            rows = table.find_elements(By.TAG_NAME, "tr")
            data = []
            for row in rows:
                cols = row.find_elements(By.TAG_NAME, "td")
                if not cols:
                    cols = row.find_elements(By.TAG_NAME, "th")
                data.append([col.text.strip() for col in cols])

            if len(data) > 1:
                df = pd.DataFrame(data[1:], columns=data[0])
                file_path = os.path.join(output_dir, filename)
                
                # Add timestamp to the beginning of the file
                current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                with open(file_path, 'w') as f:
                    f.write(f"# Data scraped on: {current_time}\n")
                    df.to_csv(f, index=False)
                
                print(f"Saved to: {file_path}\n")
                print(df.head())
                break
        else:
            print("❌ No valid tables found.")

    except Exception as e:
        print(f"❌ Error: {e}")
    finally:
        driver.quit()

if __name__ == "__main__":

    # Opponent Advanced Batting
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-batting-average-on-balls-in-play",
        "opponent_advanced_batting",
        "opponent-batting-average-on-balls-in-play.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-isolated-power",
        "opponent_advanced_batting",
        "opponent-isolated-power.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-plate-appearances",
        "opponent_advanced_batting",
        "opponent-plate-appearances.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-run-differential",
        "opponent_advanced_batting",
        "opponent-run-differential.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-secondary-average",
        "opponent_advanced_batting",
        "opponent-secondary-average.csv"
    )

    # Opponent Batting
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-at-bats-per-game",
        "opponent_batting",
        "opponent-at-bats-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-batting-average",
        "opponent_batting",
        "opponent-batting-average.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-caught-stealing-per-game",
        "opponent_batting",
        "opponent-caught-stealing-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-doubles-per-game",
        "opponent_batting",
        "opponent-doubles-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-grounded-into-double-plays-per-game",
        "opponent_batting",
        "opponent-grounded-into-double-plays-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-hit-by-pitch-per-game",
        "opponent_batting",
        "opponent-hit-by-pitch-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-hits-per-game",
        "opponent_batting",
        "opponent-hits-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-home-runs-per-game",
        "opponent_batting",
        "opponent-home-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-left-on-base-per-game",
        "opponent_batting",
        "opponent-left-on-base-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-on-base-pct",
        "opponent_batting",
        "opponent-on-base-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-on-base-plus-slugging-pct",
        "opponent_batting",
        "opponent-on-base-plus-slugging-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-rbis-per-game",
        "opponent_batting",
        "opponent-rbis-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-runners-left-in-scoring-pos-per-game",
        "opponent_batting",
        "opponent-runners-left-in-scoring-pos-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-runs-per-game",
        "opponent_batting",
        "opponent-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-sacrifice-flys-per-game",
        "opponent_batting",
        "opponent-sacrifice-flys-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-sacrifice-hits-per-game",
        "opponent_batting",
        "opponent-sacrifice-hits-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-singles-per-game",
        "opponent_batting",
        "opponent-singles-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-slugging-pct",
        "opponent_batting",
        "opponent-slugging-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-stolen-bases-attempted",
        "opponent_batting",
        "opponent-stolen-bases-attempted.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-stolen-bases-per-game",
        "opponent_batting",
        "opponent-stolen-bases-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-strikeouts-per-game",
        "opponent_batting",
        "opponent-strikeouts-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-team-left-on-base-per-game",
        "opponent_batting",
        "opponent-team-left-on-base-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-total-bases-per-game",
        "opponent_batting",
        "opponent-total-bases-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-triples-per-game",
        "opponent_batting",
        "opponent-triples-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-walks-per-game",
        "opponent_batting",
        "opponent-walks-per-game.csv"
    )

    # Opponent Batting Ratios
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-at-bats-per-home-run",
        "opponent_batting_ratios",
        "opponent-at-bats-per-home-run.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-extra-base-hit-pct",
        "opponent_batting_ratios",
        "opponent-extra-base-hit-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-hits-for-extra-bases-pct",
        "opponent_batting_ratios",
        "opponent-hits-for-extra-bases-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-hits-per-run",
        "opponent_batting_ratios",
        "opponent-hits-per-run.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-home-run-pct",
        "opponent_batting_ratios",
        "opponent-home-run-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-stolen-base-pct",
        "opponent_batting_ratios",
        "opponent-stolen-base-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-strikeout-pct",
        "opponent_batting_ratios",
        "opponent-strikeout-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-walk-pct",
        "opponent_batting_ratios",
        "opponent-walk-pct.csv"
    )

    # Opponent Fielding
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-double-plays-per-game",
        "opponent_fielding",
        "opponent-double-plays-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-errors-per-game",
        "opponent_fielding",
        "opponent-errors-per-game.csv"
    )

    # Opponent Pitching
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-earned-run-average",
        "opponent_pitching",
        "opponent-earned-run-average.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-earned-runs-against-per-game",
        "opponent_pitching",
        "opponent-earned-runs-against-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-hits-per-9",
        "opponent_pitching",
        "opponent-hits-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-home-runs-per-9",
        "opponent_pitching",
        "opponent-home-runs-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-outs-pitched-per-game",
        "opponent_pitching",
        "opponent-outs-pitched-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-shutouts",
        "opponent_pitching",
        "opponent-shutouts.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-strikeouts-per-9",
        "opponent_pitching",
        "opponent-strikeouts-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-strikeouts-per-walk",
        "opponent_pitching",
        "opponent-strikeouts-per-walk.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-walks-per-9",
        "opponent_pitching",
        "opponent-walks-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-walks-plus-hits-per-innings-pitched",
        "opponent_pitching",
        "opponent-walks-plus-hits-per-innings-pitched.csv"
    )

    # Other
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/1st-inning-runs-per-game",
        "other",
        "1st-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/2nd-inning-runs-per-game",
        "other",
        "2nd-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/3rd-inning-runs-per-game",
        "other",
        "3rd-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/4th-inning-runs-per-game",
        "other",
        "4th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/5th-inning-runs-per-game",
        "other",
        "5th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/6th-inning-runs-per-game",
        "other",
        "6th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/7th-inning-runs-per-game",
        "other",
        "7th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/8th-inning-runs-per-game",
        "other",
        "8th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/9th-inning-runs-per-game",
        "other",
        "9th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/extra-inning-runs-per-game",
        "other",
        "extra-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/first-4-innings-runs-per-game",
        "other",
        "first-4-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/first-5-innings-runs-per-game",
        "other",
        "first-5-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/first-6-innings-runs-per-game",
        "other",
        "first-6-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/games-played",
        "other",
        "games-played.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/last-2-innings-runs-per-game",
        "other",
        "last-2-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/last-3-innings-runs-per-game",
        "other",
        "last-3-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/last-4-innings-runs-per-game",
        "other",
        "last-4-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/no-run-first-inning-pct",
        "other",
        "no-run-first-inning-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-1st-inning-runs-per-game",
        "other",
        "opponent-1st-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-2nd-inning-runs-per-game",
        "other",
        "opponent-2nd-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-3rd-inning-runs-per-game",
        "other",
        "opponent-3rd-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-4th-inning-runs-per-game",
        "other",
        "opponent-4th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-5th-inning-runs-per-game",
        "other",
        "opponent-5th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-6th-inning-runs-per-game",
        "other",
        "opponent-6th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-7th-inning-runs-per-game",
        "other",
        "opponent-7th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-8th-inning-runs-per-game",
        "other",
        "opponent-8th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-9th-inning-runs-per-game",
        "other",
        "opponent-9th-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-extra-inning-runs-per-game",
        "other",
        "opponent-extra-inning-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-first-4-innings-runs-per-game",
        "other",
        "opponent-first-4-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-first-5-innings-runs-per-game",
        "other",
        "opponent-first-5-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-first-6-innings-runs-per-game",
        "other",
        "opponent-first-6-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-last-2-innings-runs-per-game",
        "other",
        "opponent-last-2-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-last-3-innings-runs-per-game",
        "other",
        "opponent-last-3-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-last-4-innings-runs-per-game",
        "other",
        "opponent-last-4-innings-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-no-run-first-inning-pct",
        "other",
        "opponent-no-run-first-inning-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-win-pct-all-games",
        "other",
        "opponent-win-pct-all-games.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-win-pct-close-games",
        "other",
        "opponent-win-pct-close-games.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/opponent-yes-run-first-inning-pct",
        "other",
        "opponent-yes-run-first-inning-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/win-pct-all-games",
        "other",
        "win-pct-all-games.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/win-pct-close-games",
        "other",
        "win-pct-close-games.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/winning-pct",
        "other",
        "winning-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/yes-run-first-inning-pct",
        "other",
        "yes-run-first-inning-pct.csv"
    )

    # Team Advanced Batting
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/batting-average-on-balls-in-play",
        "team_advanced_batting",
        "batting-average-on-balls-in-play.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/isolated-power",
        "team_advanced_batting",
        "isolated-power.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/plate-appearances",
        "team_advanced_batting",
        "plate-appearances.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/run-differential",
        "team_advanced_batting",
        "run-differential.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/secondary-average",
        "team_advanced_batting",
        "secondary-average.csv"
    )

    # Team Batting
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/at-bats-per-game",
        "team_batting",
        "at-bats-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/batting-average",
        "team_batting",
        "batting-average.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/caught-stealing-per-game",
        "team_batting",
        "caught-stealing-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/doubles-per-game",
        "team_batting",
        "doubles-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/grounded-into-double-plays-per-game",
        "team_batting",
        "grounded-into-double-plays-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/hit-by-pitch-per-game",
        "team_batting",
        "hit-by-pitch-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/hits-per-game",
        "team_batting",
        "hits-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/home-runs-per-game",
        "team_batting",
        "home-runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/left-on-base-per-game",
        "team_batting",
        "left-on-base-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/on-base-pct",
        "team_batting",
        "on-base-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/on-base-plus-slugging-pct",
        "team_batting",
        "on-base-plus-slugging-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/rbis-per-game",
        "team_batting",
        "rbis-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/runners-left-in-scoring-position-per-game",
        "team_batting",
        "runners-left-in-scoring-position-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/runs-per-game",
        "team_batting",
        "runs-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/sacrifice-flys-per-game",
        "team_batting",
        "sacrifice-flys-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/sacrifice-hits-per-game",
        "team_batting",
        "sacrifice-hits-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/singles-per-game",
        "team_batting",
        "singles-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/slugging-pct",
        "team_batting",
        "slugging-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/stolen-bases-attempted-per-game",
        "team_batting",
        "stolen-bases-attempted-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/stolen-bases-per-game",
        "team_batting",
        "stolen-bases-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/strikeouts-per-game",
        "team_batting",
        "strikeouts-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/team-left-on-base-per-game",
        "team_batting",
        "team-left-on-base-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/total-bases-per-game",
        "team_batting",
        "total-bases-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/triples-per-game",
        "team_batting",
        "triples-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/walks-per-game",
        "team_batting",
        "walks-per-game.csv"
    )

    # Team Batting Ratios
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/at-bats-per-home-run",
        "team_batting_ratios",
        "at-bats-per-home-run.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/extra-base-hit-pct",
        "team_batting_ratios",
        "extra-base-hit-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/hits-for-extra-bases-pct",
        "team_batting_ratios",
        "hits-for-extra-bases-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/hits-per-run",
        "team_batting_ratios",
        "hits-per-run.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/home-run-pct",
        "team_batting_ratios",
        "home-run-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/stolen-base-pct",
        "team_batting_ratios",
        "stolen-base-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/strikeout-pct",
        "team_batting_ratios",
        "strikeout-pct.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/walk-pct",
        "team_batting_ratios",
        "walk-pct.csv"
    )

    # Team Fielding
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/double-plays-per-game",
        "team_fielding",
        "double-plays-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/errors-per-game",
        "team_fielding",
        "errors-per-game.csv"
    )

    # Team Pitching
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/earned-run-average",
        "team_pitching",
        "earned-run-average.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/earned-runs-against-per-game",
        "team_pitching",
        "earned-runs-against-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/hits-per-9",
        "team_pitching",
        "hits-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/home-runs-per-9",
        "team_pitching",
        "home-runs-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/outs-pitched-per-game",
        "team_pitching",
        "outs-pitched-per-game.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/shutouts",
        "team_pitching",
        "shutouts.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/strikeouts-per-9",
        "team_pitching",
        "strikeouts-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/strikeouts-per-walk",
        "team_pitching",
        "strikeouts-per-walk.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/walks-per-9",
        "team_pitching",
        "walks-per-9.csv"
    )
    fetch_and_save_table(
        "https://www.teamrankings.com/mlb/stat/walks-plus-hits-per-inning-pitched",
        "team_pitching",
        "walks-plus-hits-per-inning-pitched.csv"
    )